stages:
    - build

.build_template:
    stage: build
    script:
        - ./build.sh $CI_BUILD_NAME
    artifacts:
        paths:
            - target/
    tags:
        - virt

.register_template:
    stage: register
