stages:
    - build
    - publish
    - deploy

.build_template:
    stage: build
    script:
        - ./build.sh $CI_BUILD_NAME
    artifacts:
        paths:
            - build_$CI_JOB_NAME/
    tags:
        - virt
    rules:
        - changes:
            - .gitlab-ci.yml
            - build.sh
            - generic/*
            - files/**/$CI_JOB_NAME.*
            - templates/base.json
            - templates/$CI_JOB_NAME.json

#centos-7.7:
#    extends: .build_template
#
#centos-8.1:
#    extends: .build_template
#
#debian-10.3:
#    extends: .build_template
#
#fedora-31:
#    extends: .build_template
#
#ubuntu-16.04:
#    extends: .build_template

ubuntu-18.04:
    extends: .build_template

upload_templates:
    stage: publish
    before_script:
        - mc config host add objects $OBJECTS_ENDPOINT $OBJECTS_ACCESS_KEY $OBJECTS_SECRET_KEY
    script:
        - mc cp -r build_*/ objects/compute-templates
    rules:
        - if: "$CI_COMMIT_REF_NAME == 'master'"

register_templates:
    stage: deploy
    script:
        - echo "uploading"
    needs:
        - upload_templates
    rules:
        - if: "$CI_COMMIT_REF_NAME == 'master'"
