stages:
    - build
    - deploy

.build_template:
    stage: build
    script:
        - ./build.sh $CI_BUILD_NAME
    artifacts:
        paths:
            - build/
    tags:
        - virt

.register_template:
    stage: deploy

centos77:
    extends: .build_template

centos81:
    extends: .build_template

debian103:
    extends: .build_template

fedora31:
    extends: .build_template

ubuntu1604:
    extends: .build_template

ubuntu1804:
    extends: .build_template
