variables:
    DISK_SIZE: "10240"
    HEADLESS: "1"
    MAXPROCS: "4"

stages:
    - build

ubuntu1404:
    stage: build
    script:
        - env
        - ./build.sh $CI_BUILD_NAME
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 20G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 50G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 100G
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 s3://packer-templates/$CI_BUILD_NAME-20G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 s3://packer-templates/$CI_BUILD_NAME-50G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 s3://packer-templates/$CI_BUILD_NAME-100G.qcow2
    tags:
        - packer
        - kvm

ubuntu1604:
    stage: build
    script:
        - env
        - ./build.sh $CI_BUILD_NAME
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 20G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 50G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 100G
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 s3://packer-templates/$CI_BUILD_NAME-20G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 s3://packer-templates/$CI_BUILD_NAME-50G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 s3://packer-templates/$CI_BUILD_NAME-100G.qcow2
    tags:
        - packer
        - kvm

centos68:
    stage: build
    script:
        - env
        - ./build.sh $CI_BUILD_NAME
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 20G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 50G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 100G
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 s3://packer-templates/$CI_BUILD_NAME-20G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 s3://packer-templates/$CI_BUILD_NAME-50G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 s3://packer-templates/$CI_BUILD_NAME-100G.qcow2
    tags:
        - packer
        - kvm

centos73:
    stage: build
    script:
        - env
        - ./build.sh $CI_BUILD_NAME
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 20G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 50G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 100G
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 s3://packer-templates/$CI_BUILD_NAME-20G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 s3://packer-templates/$CI_BUILD_NAME-50G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 s3://packer-templates/$CI_BUILD_NAME-100G.qcow2
    tags:
        - packer
        - kvm

debian86:
    stage: build
    script:
        - env
        - ./build.sh $CI_BUILD_NAME
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 20G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 50G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 100G
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 s3://packer-templates/$CI_BUILD_NAME-20G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 s3://packer-templates/$CI_BUILD_NAME-50G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 s3://packer-templates/$CI_BUILD_NAME-100G.qcow2
    tags:
        - packer
        - kvm

fedora25:
    stage: build
    script:
        - env
        - ./build.sh $CI_BUILD_NAME
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 20G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 50G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 100G
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 s3://packer-templates/$CI_BUILD_NAME-20G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 s3://packer-templates/$CI_BUILD_NAME-50G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 s3://packer-templates/$CI_BUILD_NAME-100G.qcow2
    tags:
        - packer
        - kvm

opensuse422:
    stage: build
    script:
        - env
        - ./build.sh $CI_BUILD_NAME
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 20G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 50G
        - qemu-img create -q -f qcow2 templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 100G
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2
        - virt-resize --expand /dev/sda2 templates/$CI_BUILD_NAME/packer_output/$CI_BUILD_NAME templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-20G.qcow2 s3://packer-templates/$CI_BUILD_NAME-20G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-50G.qcow2 s3://packer-templates/$CI_BUILD_NAME-50G.qcow2
        - s3cmd put -P templates/$CI_BUILD_NAME/$CI_BUILD_NAME-100G.qcow2 s3://packer-templates/$CI_BUILD_NAME-100G.qcow2
    tags:
        - packer
        - kvm
